alert("Selamat Hari Lebaran")
alert("Taqabbalallahu Minna Wa Minkum")
alert("Minal aidzin wal faidzin")
alert("Mohon maaf lahir dan batin, kalau ada kesalahan atau kata yang kurang berkenan🙏")
alert("Semoga kita dipertemukan dg Ramadhan tahun depan")
