alert("Selamat Hari Lebaran")
alert("Taqabbalallahu Minna Wa Minkum")
alert("Minal aidzin Wal faidzin")
alert("Mohon maaf lahir dan batin, kalau saya ada kesalahan atau kata yang kurang berkenan🙏")
alert("Semoga kita dipertemukan dg Ramadhan tahun depan")
